# Generated by Django 5.2.1 on 2025-06-10 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0002_remove_deposit_plan_remove_deposit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('connectpay_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ConnectPay Transaction ID')),
                ('method', models.CharField(choices=[('USDT_BEP20', 'USDT (BEP20)'), ('PIX', 'PIX')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10, verbose_name='Status')),
                ('coinpayments_txn_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CoinPayments TXN ID')),
                ('payment_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Payment Address (USDT)')),
                ('qrcode_url', models.URLField(blank=True, null=True, verbose_name='QR Code URL (CoinPayments)')),
                ('status_url', models.URLField(blank=True, null=True, verbose_name='Status URL (CoinPayments)')),
                ('pix_qr_code_payload', models.TextField(blank=True, null=True, verbose_name='PIX QR Code Payload (Copia e Cola)')),
                ('pix_qr_code_image_url', models.URLField(blank=True, null=True, verbose_name='PIX QR Code Image URL')),
                ('pix_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIX Key')),
                ('pix_key_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIX Key Type')),
                ('pix_beneficiary_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='PIX Beneficiary Name')),
                ('transaction_hash', models.CharField(blank=True, max_length=255, verbose_name='Transaction Hash/ID')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_intended_for', to='investments.plan', verbose_name='Intended Plan (optional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('tx_type', models.CharField(choices=[('TRANSFER', 'Token transfer'), ('CONTRACT', 'Contract call'), ('WITHDRAWAL', 'Withdrawal')], max_length=20, verbose_name='Transaction Type')),
                ('transaction_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20, verbose_name='Transaction Status')),
                ('tx_hash', models.CharField(max_length=100, unique=True, verbose_name='Transaction Hash')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('fee', models.CharField(blank=True, max_length=50, verbose_name='Fee')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_txs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Onchain Transaction',
                'verbose_name_plural': 'Onchain Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
