# Generated by Django 5.2.1 on 2025-06-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
