# Generated by Django 5.2.1 on 2025-06-10 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('id', models.CharField(choices=[('FREE', 'Hoo Free'), ('PANDORA', 'Hoo Pandora'), ('TITAN', 'Hoo Titan'), ('CALLISTO', 'Hoo Callisto')], max_length=20, primary_key=True, serialize=False, verbose_name='Plan ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('image_src', models.CharField(blank=True, max_length=255, verbose_name='Image Source URL')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color Hex Code (e.g., #RRGGBB)')),
                ('min_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Investment Value')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Tag (e.g., Popular, Premium)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('daily_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Daily Yield Percentage')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duration in Days')),
                ('cap_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Yield Cap Percentage')),
                ('withdrawal_policy', models.CharField(blank=True, help_text="Descreva a política de saque. Ex: 'Saques diários', 'Saques semanais', etc.", max_length=100, verbose_name='Política de Saque')),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
                'ordering': ['min_value'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('connectpay_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ConnectPay Transaction ID')),
                ('method', models.CharField(choices=[('USDT_BEP20', 'USDT (BEP20)'), ('PIX', 'PIX')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10, verbose_name='Status')),
                ('coinpayments_txn_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CoinPayments TXN ID')),
                ('payment_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Payment Address (USDT)')),
                ('qrcode_url', models.URLField(blank=True, null=True, verbose_name='QR Code URL (CoinPayments)')),
                ('status_url', models.URLField(blank=True, null=True, verbose_name='Status URL (CoinPayments)')),
                ('pix_qr_code_payload', models.TextField(blank=True, null=True, verbose_name='PIX QR Code Payload (Copia e Cola)')),
                ('pix_qr_code_image_url', models.URLField(blank=True, null=True, verbose_name='PIX QR Code Image URL')),
                ('pix_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIX Key')),
                ('pix_key_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIX Key Type')),
                ('pix_beneficiary_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='PIX Beneficiary Name')),
                ('transaction_hash', models.CharField(blank=True, max_length=255, verbose_name='Transaction Hash/ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_intended_for', to='investments.plan', verbose_name='Intended Plan (optional)')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Activation Code')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date/Time')),
                ('next_yield_date', models.DateField(blank=True, null=True, verbose_name='Next Yield Date')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progress Percentage')),
                ('total_yielded', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Yielded Amount')),
                ('investment_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('YIELDING', 'Yielding'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20, verbose_name='Investment Status')),
                ('deposit_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_investment', to='investments.deposit', verbose_name='Source Deposit (optional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('type', models.CharField(choices=[('YIELD', 'Yield'), ('REFERRAL', 'Referral Bonus'), ('BONUS', 'Bonus'), ('CASHBACK', 'Cashback'), ('REFUND', 'Refund')], max_length=20, verbose_name='Earning Type')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin Description')),
                ('description', models.TextField(blank=True, verbose_name='Detailed Description')),
                ('earning_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('AVAILABLE', 'Available for Withdrawal')], default='PENDING', max_length=20, verbose_name='Earning Status')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effective/Credited Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('investment_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_earnings', to='investments.investment', verbose_name='Source Investment (optional)')),
            ],
            options={
                'verbose_name': 'Earning',
                'verbose_name_plural': 'Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('tx_type', models.CharField(choices=[('TRANSFER', 'Token transfer'), ('CONTRACT', 'Contract call'), ('WITHDRAWAL', 'Withdrawal')], max_length=20, verbose_name='Transaction Type')),
                ('transaction_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20, verbose_name='Transaction Status')),
                ('tx_hash', models.CharField(max_length=100, unique=True, verbose_name='Transaction Hash')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('fee', models.CharField(blank=True, max_length=50, verbose_name='Fee')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_txs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Onchain Transaction',
                'verbose_name_plural': 'Onchain Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
