# Generated by Django 5.2.1 on 2025-06-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_remove_deposit_plan_remove_deposit_user'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='deposit_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_investment', to='payments.deposit', verbose_name='Source Deposit (optional)'),
        ),
        migrations.RemoveField(
            model_name='earning',
            name='investment_source',
        ),
        migrations.RemoveField(
            model_name='earning',
            name='user',
        ),
        migrations.RemoveField(
            model_name='onchaintransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Earning',
        ),
        migrations.DeleteModel(
            name='OnchainTransaction',
        ),
    ]
