# Generated by Django 5.2.1 on 2025-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deposit_coinpayments_txn_id_deposit_payment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Disponível'),
        ),
    ]
