# Generated by Django 5.2.1 on 2025-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_country_alter_user_cpf_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Investment Plan', 'verbose_name_plural': 'Investment Plans'},
        ),
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color Hex Code (e.g., #RRGGBB)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_src',
            field=models.CharField(blank=True, max_length=255, verbose_name='Image Source URL'),
        ),
        migrations.AddField(
            model_name='plan',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Investment Value'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cap_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Yield Cap Percentage'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='daily_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Daily Yield Percentage'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='Duration in Days'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.CharField(choices=[('FREE', 'Hoo Free'), ('PANDORA', 'Hoo Pandora'), ('TITAN', 'Hoo Titan'), ('CALLISTO', 'Hoo Callisto')], max_length=20, primary_key=True, serialize=False, verbose_name='Plan ID'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plan Name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tag (e.g., Popular, Premium)'),
        ),
    ]
