# Generated by Django 5.2.1 on 2025-06-05 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_plan_options_plan_color_plan_image_src_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
        migrations.AlterModelOptions(
            name='earning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Earning', 'verbose_name_plural': 'Earnings'},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-start_date'], 'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.AlterModelOptions(
            name='onchaintransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Onchain Transaction', 'verbose_name_plural': 'Onchain Transactions'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['min_value'], 'verbose_name': 'Investment Plan', 'verbose_name_plural': 'Investment Plans'},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='next_release',
        ),
        migrations.AddField(
            model_name='deposit',
            name='pix_beneficiary_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='PIX Beneficiary Name'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PIX Key'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pix_key_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PIX Key Type'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pix_qr_code_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='PIX QR Code Image URL'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='pix_qr_code_payload',
            field=models.TextField(blank=True, null=True, verbose_name='PIX QR Code Payload (Copia e Cola)'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_intended_for', to='api.plan', verbose_name='Intended Plan (optional)'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='earning',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effective/Credited Date'),
        ),
        migrations.AddField(
            model_name='earning',
            name='investment_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_earnings', to='api.investment', verbose_name='Source Investment (optional)'),
        ),
        migrations.AddField(
            model_name='investment',
            name='deposit_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_investment', to='api.deposit', verbose_name='Source Deposit (optional)'),
        ),
        migrations.AddField(
            model_name='investment',
            name='next_yield_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Yield Date'),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_yielded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Yielded Amount'),
        ),
        migrations.AddField(
            model_name='onchaintransaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='coinpayments_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CoinPayments TXN ID'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('USDT_BEP20', 'USDT (BEP20)'), ('PIX', 'PIX')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Payment Address (USDT)'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='qrcode_url',
            field=models.URLField(blank=True, null=True, verbose_name='QR Code URL (CoinPayments)'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status_url',
            field=models.URLField(blank=True, null=True, verbose_name='Status URL (CoinPayments)'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transaction Hash/ID'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='description',
            field=models.TextField(blank=True, verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='origin',
            field=models.CharField(max_length=100, verbose_name='Origin Description'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('AVAILABLE', 'Available for Withdrawal')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='type',
            field=models.CharField(choices=[('YIELD', 'Yield'), ('REFERRAL', 'Referral Bonus'), ('BONUS', 'Bonus'), ('CASHBACK', 'Cashback'), ('REFUND', 'Refund')], max_length=20, verbose_name='Earning Type'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Invested Amount'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Activation Code'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='expiration_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='api.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='progress_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Progress Percentage'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date/Time'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('YIELDING', 'Yielding'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='onchaintransaction',
            name='fee',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='onchaintransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='onchaintransaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='onchaintransaction',
            name='tx_hash',
            field=models.CharField(max_length=100, unique=True, verbose_name='Transaction Hash'),
        ),
        migrations.AlterField(
            model_name='onchaintransaction',
            name='tx_type',
            field=models.CharField(choices=[('TRANSFER', 'Token transfer'), ('CONTRACT', 'Contract call'), ('WITHDRAWAL', 'Withdrawal')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='onchaintransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_txs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='onchaintransaction',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Value'),
        ),
    ]
