# Generated by Django 5.2.1 on 2025-06-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_deposit_options_alter_earning_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='connectpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ConnectPay Transaction ID'),
        ),
    ]
