# Generated by Django 5.2.1 on 2025-06-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_deposit_connectpay_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='withdrawal_policy',
            field=models.CharField(blank=True, help_text="Descreva a política de saque. Ex: 'Saques diários', 'Saques semanais', etc.", max_length=100, verbose_name='Política de Saque'),
        ),
    ]
