# Generated by Django 5.2.1 on 2025-06-10 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0003_alter_investment_deposit_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('type', models.CharField(choices=[('YIELD', 'Yield'), ('REFERRAL', 'Referral Bonus'), ('BONUS', 'Bonus'), ('CASHBACK', 'Cashback'), ('REFUND', 'Refund')], max_length=20, verbose_name='Earning Type')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin Description')),
                ('description', models.TextField(blank=True, verbose_name='Detailed Description')),
                ('earning_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('AVAILABLE', 'Available for Withdrawal')], default='PENDING', max_length=20, verbose_name='Earning Status')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Effective/Credited Date')),
                ('investment_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_earnings', to='investments.investment', verbose_name='Source Investment (optional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Earning',
                'verbose_name_plural': 'Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('CUSTOM', 'Custom Period Report')], max_length=20, verbose_name='Report Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Deposits')),
                ('total_investments', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Investments')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Earnings')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Active Users')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='New Users')),
                ('detailed_data', models.JSONField(blank=True, default=dict, verbose_name='Detailed Data')),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-created_at'],
                'unique_together': {('report_type', 'start_date', 'end_date')},
            },
        ),
    ]
