# Generated by Django 5.2.1 on 2025-06-10 22:24

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Habilitado')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Habilitado')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push Notifications Habilitadas')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='Notificações In-App Habilitadas')),
                ('notification_types', models.JSONField(blank=True, default=notifications.models.get_default_notification_types, help_text='Configurações específicas por tipo de notificação', verbose_name='Configurações por Tipo')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Início do período de silêncio', null=True, verbose_name='Início do Silêncio')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Fim do período de silêncio', null=True, verbose_name='Fim do Silêncio')),
                ('digest_frequency', models.CharField(choices=[('IMMEDIATE', 'Imediato'), ('HOURLY', 'A cada hora'), ('DAILY', 'Diário'), ('WEEKLY', 'Semanal'), ('NEVER', 'Nunca')], default='IMMEDIATE', max_length=10, verbose_name='Frequência do Resumo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('notification_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('INVESTMENT', 'Investimento'), ('EARNING', 'Ganho'), ('WITHDRAWAL', 'Saque'), ('REFERRAL', 'Indicação'), ('SYSTEM', 'Sistema'), ('SECURITY', 'Segurança'), ('PROMOTION', 'Promoção'), ('WELCOME', 'Bem-vindo'), ('KYC', 'Verificação KYC')], max_length=20, verbose_name='Tipo de Notificação')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'Notificação no App')], max_length=10, verbose_name='Canal de Notificação')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto/Título')),
                ('content', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('html_content', models.TextField(blank=True, verbose_name='Conteúdo HTML (para email)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template Padrão')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de variáveis disponíveis no template', verbose_name='Variáveis')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'ordering': ['notification_type', 'channel'],
                'unique_together': {('notification_type', 'channel', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notification_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('INVESTMENT', 'Investimento'), ('EARNING', 'Ganho'), ('WITHDRAWAL', 'Saque'), ('REFERRAL', 'Indicação'), ('SYSTEM', 'Sistema'), ('SECURITY', 'Segurança'), ('PROMOTION', 'Promoção'), ('WELCOME', 'Bem-vindo'), ('KYC', 'Verificação KYC')], max_length=20, verbose_name='Tipo de Notificação')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'Notificação no App')], max_length=10, verbose_name='Canal')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto/Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('html_content', models.TextField(blank=True, verbose_name='Conteúdo HTML')),
                ('notification_status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviada'), ('DELIVERED', 'Entregue'), ('READ', 'Lida'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Status da Notificação')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('recipient_info', models.JSONField(blank=True, default=dict, help_text='Email, telefone, ou dados do destinatário', verbose_name='Info do Destinatário')),
                ('variables_used', models.JSONField(blank=True, default=dict, help_text='Variáveis usadas no processamento do template', verbose_name='Variáveis Usadas')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('action_url', models.URLField(blank=True, verbose_name='URL da Ação')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate', verbose_name='Template Usado')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'notification_status'], name='notificatio_user_id_d3dceb_idx'), models.Index(fields=['notification_type', 'channel'], name='notificatio_notific_bc52a4_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
